#include "audio.h"
#include <Wire.h>
#include <esp_heap_caps.h>
#include <math.h>
#include "config.h"
namespace{constexpr int SDA_=45,SCL_=0,DIN_=4,WS_=3,DOUT_=48,BCLK_=17,AMP_=18;void L16(uint8_t*p,uint16_t v){p[0]=v;p[1]=v>>8;}void L32(uint8_t*p,uint32_t v){p[0]=v;p[1]=v>>8;p[2]=v>>16;p[3]=v>>24;}uint16_t R16(const uint8_t*p){return p[0]|p[1]<<8;}uint32_t R32(const uint8_t*p){return p[0]|p[1]<<8|p[2]<<16|p[3]<<24;}}
VoiceS3rAudio::VoiceS3rAudio():echo_(I2S_NUM_0){}
bool VoiceS3rAudio::Probe(uint8_t a){Wire.beginTransmission(a);return Wire.endTransmission()==0;}
void VoiceS3rAudio::Amp(bool e){digitalWrite(AMP_,e?HIGH:LOW);Serial.printf("[INFO] AMP GPIO18: %s\n",e?"HIGH":"LOW");}
bool VoiceS3rAudio::Begin(){Serial.printf("[INFO] PSRAM: %u bytes\n",ESP.getPsramSize());pinMode(AMP_,OUTPUT);Amp(false);Wire.begin(SDA_,SCL_,100000);bool es=Probe(0x18),pi=Probe(0x43);Serial.printf("[INFO] ES8311 0x18: %s\n",es?"検出":"未検出");Serial.printf("[INFO] PI4IOE 0x43: %s\n",pi?"検出":"未検出（正常）");if(!es)return false;bool all=echo_.init(kRate,SDA_,SCL_,DIN_,WS_,DOUT_,BCLK_,Wire);Serial.printf("[INFO] EchoBase init: %d（PI4IOEなしなら0で継続）\n",all);echo_.setSpeakerVolume(55);echo_.setMicGain(ES8311_MIC_GAIN_6DB);wav_=static_cast<uint8_t*>(heap_caps_malloc(kHead+kMax,MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT));io_=static_cast<int32_t*>(heap_caps_malloc(kN*4,MALLOC_CAP_8BIT));ready_=wav_&&io_;return ready_;}
bool VoiceS3rAudio::TestSpeaker(){if(!ready_)return false;Amp(true);for(size_t i=0;i<kN;i++)io_[i]=static_cast<int32_t>(sin(2*PI*1000*i/kRate)*0x18000000);echo_.play(reinterpret_cast<uint8_t*>(io_),kN*4);Amp(false);return true;}
bool VoiceS3rAudio::StartRecording(){if(!ready_||recording_)return false;Amp(false);bytes_=0;voice_=stop_=false;started_=last_voice_=last_log_=millis();recording_=true;Serial.println("[INFO] 録音開始");return true;}
void VoiceS3rAudio::UpdateRecording(){if(!recording_)return;if(millis()-started_>=config::kMaxRecordingMs||bytes_>=kMax){stop_=true;return;}echo_.record(reinterpret_cast<uint8_t*>(io_),kN*4);int64_t p=0;int16_t*d=reinterpret_cast<int16_t*>(wav_+kHead+bytes_);for(size_t i=0;i<kN;i++){int16_t s=io_[i]>>16;d[i]=s;p+=int32_t(s)*s;}bytes_+=kN*2;int32_t rms=sqrt(double(p)/kN);if(rms>=config::kSilenceRms){voice_=true;last_voice_=millis();}if(millis()-last_log_>=250){last_log_=millis();Serial.printf("[INFO] Mic RMS: %ld\n",long(rms));}if(voice_&&millis()-last_voice_>=config::kSilenceStopMs)stop_=true;}
bool VoiceS3rAudio::StopRecording(){if(!recording_)return false;recording_=false;Header();Serial.printf("[INFO] 録音終了: %u bytes voice=%d\n",unsigned(bytes_),voice_);return voice_&&bytes_>=kRate;}
bool VoiceS3rAudio::PlayWav(const uint8_t*d,size_t z){if(!ready_||!d||z<44||memcmp(d,"RIFF",4))return false;uint16_t ch=R16(d+22),bits=R16(d+34);uint32_t rate=R32(d+24),n=R32(d+40);if(ch!=1||bits!=16||rate!=kRate||44+n>z)return false;Amp(true);const int16_t*p=reinterpret_cast<const int16_t*>(d+44);size_t samples=n/2;for(size_t o=0;o<samples;o+=kN){size_t c=min(kN,samples-o);for(size_t i=0;i<c;i++)io_[i]=int32_t(p[o+i])<<16;echo_.play(reinterpret_cast<uint8_t*>(io_),c*4);}Amp(false);return true;}
void VoiceS3rAudio::Header(){uint8_t*h=wav_;memcpy(h,"RIFF",4);L32(h+4,36+bytes_);memcpy(h+8,"WAVEfmt ",8);L32(h+16,16);L16(h+20,1);L16(h+22,1);L32(h+24,kRate);L32(h+28,kRate*2);L16(h+32,2);L16(h+34,16);memcpy(h+36,"data",4);L32(h+40,bytes_);}bool VoiceS3rAudio::IsRecording()const{return recording_;}bool VoiceS3rAudio::ShouldAutoStop()const{return stop_;}const uint8_t*VoiceS3rAudio::WavData()const{return wav_;}size_t VoiceS3rAudio::WavSize()const{return kHead+bytes_;}
